# Generated by Django 3.2.8 on 2021-10-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Описание')),
                ('published', models.BooleanField(default=True, verbose_name='Публиковать')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задании',
                'ordering': ('created_at',),
            },
        ),
    ]
