# Generated by Django 3.2.8 on 2021-10-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created_at'], 'verbose_name': 'Задание', 'verbose_name_plural': 'Задании'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
    ]
