# Generated by Django 3.2.8 on 2021-10-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20211008_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Открыта'), ('close', 'Закрыта')], default='open', max_length=20, verbose_name='Статус'),
        ),
    ]
